jobs:
  build:
    docker:
      - image: circleci/ruby:rc-browsers-legacy
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec rspec